artifacts_root: artifacts

data ingestion:
  root dir: artifacts/data_ingestion
  source_URL: https://github.com/Parthsarthi-lab/test/raw/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt