artifacts_root: artifacts

data ingestion:
  root dir: artifacts/data_ingestion
  source_URL: https://github.com/Parthsarthi-lab/test/raw/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion